blog/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path("", views.PostList.as_view(), name="posts-list"),
    path("<slug:slug>/", views.PostDetail.as_view(), name="post_detail"),
]

course/urls.py
from django.urls import path


from .views import ChapterDetailView
from .views import CourseDetailView, CourseListView

urlpatterns = [
    path("", CourseListView.as_view(), name="course-list"),
    path("<int:pk>/", CourseDetailView.as_view(), name="course-detail"),
    path("lessons/<int:pk>/", ChapterDetailView.as_view(), name="lesson-detail"),
]

mojganrajabi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import HomeView, AboutView

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("about/", AboutView.as_view(), name="about"),
    path("admin/", admin.site.urls),
    path("courses/", include("course.urls")),
    path("user/", include("users.urls")),
    path("payment/", include("payment.urls")),
    path("blog/", include("blog.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("buy/<int:course_pk>/", views.buy, name="buy"),
]

users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

urlpatterns = [
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", views.signup, name="signup"),
    path("dashboard/", views.dashboard, name="dashboard"),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User


STATUS = ((0, "Draft"), (1, "Publish"))


class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="blog_posts"
    )
    updated_on = models.DateTimeField(auto_now=True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return self.title


class About(models.Model):
    title = models.CharField(max_length=200, unique=False)
    content = models.TextField()

    def __str__(self):
        return self.title

course/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class Course(models.Model):
    PAYMENT_STATUS = (
        ("free", "Free"),
        ("paid", "Paid"),
    )
    image = models.ImageField(upload_to="images/courses", default="course.jpg")
    promotion = models.FileField(upload_to="videos/courses/")
    title = models.CharField(max_length=127)
    subtitle = models.CharField(max_length=255)
    detail = models.TextField()
    date_published = models.DateField(null=True, blank=True)
    date_created = models.DateField(auto_now_add=True)
    date_modified = models.DateField(auto_now=True)
    price = models.DecimalField(max_digits=5, decimal_places=2, default=99.99)
    payment_status = models.CharField(
        max_length=4, choices=PAYMENT_STATUS, default="paid"
    )
    # users = models.ManyToManyField(User)
    link = models.CharField(max_length=255, default="somelink.com/course")

    def get_absolute_url(self):
        return reverse("course-detail", kwargs={"pk": self.pk})

    def lessons(self):
        return [
            lesson
            for chapter in self.chapter_set.all()
            for lesson in chapter.lesson_set.all()
        ]

    def number_of_lessons(self):
        return len(self.lessons())

    def __str__(self):
        return self.title


class Chapter(models.Model):
    title = models.CharField(max_length=256)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Lesson(models.Model):
    PAYMENT_STATUS = (
        ("free", "Free"),
        ("paid", "Paid"),
    )
    video = models.FileField(upload_to=f"videos/lessons/")
    title = models.CharField(max_length=128)
    payment_status = models.CharField(
        max_length=4, choices=PAYMENT_STATUS, default="paid"
    )
    chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE)

    # list of users bought the course of the lesson.
    def users(self):
        pass

    def get_absolute_url(self):
        return reverse("lesson-detail", kwargs={"pk": self.pk})

    def course(self):
        return self.chapter.course

    def __str__(self):
        return self.title

payment/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class SignupForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

blog/views.py
from django.shortcuts import render
from django.views import generic
from .models import Post, About


class PostList(generic.ListView):
    queryset = Post.objects.filter(status=1).order_by("-created_on")
    template_name = "blog/posts.html"


class PostDetail(generic.DetailView):
    model = Post
    template_name = "blog/post_detail.html"

course/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.contrib.auth.models import User
from .models import Chapter, Course, Lesson


class CourseAccessMixin(UserPassesTestMixin):
    def test_func(self):
        user = User.objects.get(username=self.request.user.username)
        print(dir(user))
        url_list = [item for item in self.request.get_full_path().split("/") if item]
        course_id = url_list[-1]
        course = Course.objects.get(pk=course_id)
        print(dir(course.users))
        usernames = [user.username for user in course.users.all()]
        return self.request.user.username in usernames


class CourseListView(ListView):
    model = Course
    template_name = "course/courses.html"
    context_object_name = "courses"


class CourseDetailView(LoginRequiredMixin, DetailView):
    model = Course
    template_name = "course/course_detail.html"
    context_object_name = "course"


class ChapterDetailView(DetailView):
    model = Chapter
    template_name = "course/chapter_detail.html"
    context_object_name = "chapter"


class ChapterDetailView(DetailView):
    model = Lesson
    template_name = "course/lesson_detail.html"
    context_object_name = "lesson"

mojganrajabi/views.py
from django.shortcuts import render
from django.views.generic import ListView

from course.models import Course
from blog.models import About


def index(request):
    return render(request, "home/index.html")


class HomeView(ListView):
    models = Course
    context_object_name = "courses"
    template_name = "home/index.html"
    queryset = Course.objects.all()


class AboutView(ListView):
    model = About
    template_name = "home/about.html"

payment/views.py
from multiprocessing import context
from django.shortcuts import render
from course.models import Course


def buy(request, course_pk):
    course = Course.objects.get(pk=course_pk)
    bank_account = "1234-9876-8778-00998"
    email = "mojgan.rajabi@gmail.com"
    return render(
        request,
        "payment/buy.html",
        {"course": course, "bank_account": bank_account, "email": email},
    )

users/views.py
from django.shortcuts import render, redirect

from .forms import SignupForm


def dashboard(reqeust):
    return render(reqeust, "users/dashboard.html")


def signup(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("dashboard")
    else:
        form = SignupForm()
    print(dir(form))
    return render(request, "users/signup.html", {"form": form})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'fonts/fontawesome/css/all.min.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    
    <header>
      {% include "components/navbar.html"%}
    </header>
    <main>
      {% block content %}
      {% endblock content %}
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

templates/blog/post_detail.html
{% extends 'base.html' %} 
{% comment %} {% block title %}{{object.title}}{% endblock title %} {% endcomment %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <div class="card-body">
        <h1>{% block title %} {{ object.title }} {% endblock title %}</h1>
        <p class=" text-muted">{{ post.author }} | {{ post.created_on }}</p>
        <p class="card-text ">{{ object.content | safe }}</p>
      </div>
    </div>
    {% comment %} {% block sidebar %} {% include 'sidebar.html' %} {% endblock sidebar %} {% endcomment %}
  </div>
</div>

{% endblock content %}

templates/blog/posts.html
{% extends 'base.html' %}
{% block title %}Blog posts{% endblock title %}
{% block content %}
<div class="container">
  <div class="row">
      <!-- Blog Entries Column -->
      <div class="col-md-8 mt-4 left">
          {% for post in post_list %}
          <div class="card mb-4">
              <div class="card-body">
                <h2 class="card-title">{{ post.title }}</h2>
                <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on}} </p>
                <p class="card-text">{{post.content|slice:":200" }}</p>
                <a href="{% url 'post_detail' post.slug  %}" class="btn btn-primary">Read More &rarr;</a>
              </div>
          </div>
          {% endfor %}
      </div>
      {% comment %} {% block sidebar %} {% include 'components/sidebar.html' %} {% endblock sidebar %} {% endcomment %}
  </div>
</div>
{% endblock content %}

templates/components/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark  bg-dark">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <a class="navbar-brand" href="{% url 'home' %}">Mojgan Rajabi</a>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'course-list' %}">Courses</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'posts-list' %}">Blog</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'about' %}">About</a>
        </li>
      </ul>

      <div class="d-flex">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="#"><i class="fa-brands fa-instagram"></i></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#"><i class="fa-brands fa-facebook-square"></i></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#"><i class="fa-brands fa-linkedin"></i></i></a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>

templates/components/sidebar.html
{% block sidebar %}

<style>
        .card{
            box-shadow: 0 16px 48px #E3E7EB;
        }

</style>

<!-- Sidebar Widgets Column -->
<div class="col-md-4 float-right ">
<div class="card my-4">
  <h5 class="card-header">About Us</h5>
  <div class="card-body">
    <p class="card-text">{{ about }}</p>
  </div>
</div>
</div>

{% endblock sidebar %}

templates/course/chapter_detail.html
{% extends 'base.html' %}
{% block title %}{% endblock title %}
{% block content %}
<div class="videoplayer">
  <video width="320" height="240" controls>
    <source src="{{ course.promotion.url }}" type="video/mp4">
  </video>
</div>
<div>
  {% comment %} <ul class="chapters">
    {% for chapter in chapters %}
      <li class="chapter">
        <h3>{{ chapter.title }}</h3>
        <ul class="lesssons">
          {% for lesson in chapter.lesson_set.all %}
            <li class="lesson">
              <a href="#">{{ lesson.title }}</a>
            </li>
          {% endfor %}
        </ul> <!-- end of a lesson videos. -->
      </li> <!-- end of a chapter-->
    {% endfor %}
  </ul>  <!-- end of chapters. --> {% endcomment %}
</div>
{% endblock content %}

templates/course/course_detail.html
{% extends 'base.html' %}
{% block title %}{{ course.title }}{% endblock title %}
{% block content %}
<div class="container">
  <h1 class="mt-5">{{ course.title }}</h1>
  <h2>{{ course.subtitle }}</h2>
  <p>{{ course.detail }}</p>
  <div>
    <ul>
      {% for chapter in course.chapter_set.all  %}
        <li>{{ chapter.title }}</li>
      {% endfor %}
    </ul>
  </div>
  <a href="{{ course.link }}" class="btn btn-primary">Go to course</a>
</div>
{% endblock content %}

templates/course/courses.html
{% extends 'base.html' %}
{% block title %}All courses{% endblock title %}
{% block content %}

<div class="container mt-5">
  <div class="row row-cols-1 row-cols-md-3 g-4">
  {% for course in courses %}
    <div class="col">
      <div class="card">
        <video controls>
          <source src="{{ course.promotion.url }}" type="video/mp4">
        </video>
        <div class="card-body">
          <h5 class="card-title">{{ course.title }}</h5>
          <p class="card-text">{{ course.subtitle }}</p>
          <a href="{% url  'course-detail' course.pk %}" class="btn btn-primary">Course detail</a>
        </div> <!-- end of card body -->
        <div class="card-footer">
          <span class="px-3"><i class="fa-solid fa-video"></i><small class="m-1">{{ course.number_of_lessons }}</small></span>
          <span><i class="fa-solid fa-calendar-days"></i><small class="m-1">{{ course.date_published }}</small></span>
          <span><i class="fa-solid fa-dollar-sign"></i><small class="m-1">{{ course.price }}</small></sapn>
        </div> <!-- card footer -->
      </div> <!-- end of a card -->
    </div> <!-- end of col -->
  {% endfor %}
  </div> <!-- end of grid system -->
</div>
{% endblock content %}

templates/course/lesson_detail.html
{% extends 'base.html' %}
{% block title %}{{lesson.title}}{% endblock title %}
{% block content %}
<!-- Lessons conteainer -->
<div class="lessons">
  <!-- Content of a lessons / player + chapters -->
  <div class="content">
    <div class="player">
      <video controls>
        <source src="{{ lesson.video.url }}" type="video/mp4">
      </video>
    </div>
    <div class="chapters">
      <ul>
        {% for chapter in lesson.course.chapter_set.all %}
        <li class="chapter">
          <h3 class="accordion">{{ chapter.title }}</h3>
          <ul class="panel">
          {% for lesson in chapter.lesson_set.all %}
          <li class="lesson">
            {% if lesson.payment_status == "paid" and lesson.course not in user.course_set.all %}
            <a href="{% url 'buy' lesson.course.pk %}">
              <i class="fa-solid fa-play"></i>
              {{ lesson.title }}
              <i class="fa-solid fa-lock"></i>
            </a>
            {% else %}  <!-- if course is free -->
            <a href="{% url 'lesson-detail' lesson.pk %}">
              <i class="fa-solid fa-play"></i>
              {{ lesson.title }}
              <i class="fa-solid fa-lock-open"></i>
            </a>
            {% endif %}
          </li> <!-- end of a lesson-->
          {% endfor %}
          </ul> <!-- end of lessons-->
        </li> <!-- end of a chapter-->
        {% endfor %} 
      </ul> 
  </div>  <!-- end of chapters. -->
</div>
<script>
  var acc = document.getElementsByClassName("accordion");
  var i;
  
  for (i = 0; i < acc.length; i++) {
    acc[i].addEventListener("click", function() {
      this.classList.toggle("active");
      var panel = this.nextElementSibling;
      if (panel.style.display === "block") {
        panel.style.display = "none";
      } else {
        panel.style.display = "block";
      }
    }); // end of function.
  } // end for
  </script>
{% endblock content %}

templates/home/about.html
{% extends 'base.html' %}
{% block title %}About Me{% endblock title %}
{% block content %}
<div class="container mt-5 px-5">
  {% for about  in object_list  %} 
    <div class="py-3">
      <h3>{{ about.title }}</h3>
      <p>{{ about.content }}</p>
      <hr>
    </div>
  {% endfor %}
</div>
{% endblock content %}

templates/home/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Mojgan Rajabi{% endblock title %}
{% block content %}


<div class="px-4 py-5 my-5 text-center">
  <img class="d-block mx-auto mb-4" src="{% static 'images/m.png' %}" alt="logo" width="72">
  <h1 class="display-5 fw-bold">Learn  modern computation.</h1>
  <div class="col-lg-6 mx-auto">
    <p class="lead mb-4">With 10+ years of experience I will teach you modern way of data analysis which help to get job in the industry.</p>
    <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
      <a href="{% url 'course-list' %}" class="btn btn-primary btn-lg px-4 gap-3">Courses</a>
      <a href="{% url 'posts-list' %}" class="btn btn-outline-secondary btn-lg px-4">Blog Posts</a>
    </div>
  </div>
</div>

{% endblock content %}

templates/payment/buy.html
{% extends 'base.html' %}
{% block title %}Buy this course{% endblock title %}
{% block content %}
<div class="buy">
  <h3>{{ course.title }}</h3> 
  <h3 class="price">${{ course.price }}</h3> 
  <hr>
  <div class="how">
    <h3>How to unlock this course?</h3>
    <ol>
      <li>Pay the course price to <em>{{ bank_account }}</em></li>
      <li>Email me at <em>{{ email }}</em> including <em>bank recipt</em>, your <em>username</em> and <em>course name</em>.</li>
    </ol>
    <p>After check the recipt I will give you access to the course.</p>
  </div>
  <div class="thanks">
    <p>Thank you for considering buying this course.</p>
    <p>I promise to implement online payment solution very soon.</p>
    <p> - Regards <strong>Mojgan Rajabi</strong></p>
  </div>
</div>
{% endblock content %}

templates/users/dashboard.html
<h1>dashboard page</h1>

templates/users/login.html
{% extends 'base.html' %}
{% block title %}Login{% endblock title %}
{% block content %}
<div class="login-container">
  <form class="login-form" action="" method="POST" >
    {% csrf_token %}
    {% if form.errors %}
    <p class="error">Your username and password didn't match. Please try again.</p>
    {% endif %}

    {{ form.username.label_tag }}
    {{ form.username }}
    {{ form.password.label_tag }}
    {{ form.password}}
    <input type="submit" value="Login">
    <input type="hidden" name="next" value="{{ next }}">
  </form>
</div>
{% endblock content %}

templates/users/loginmodal.html
{{ form.as_p }}

<div id="id01" class="modal">
  <form class="modal-form animate" action="{% url 'login' %}" method="post">
    {% csrf_token %}
    <div class="close-container">
    <span onclick="document.getElementById('id01').style.display='none'" class="close" title="Close Modal">&times;</span>
    </div>

    <div class="modal-form-elements">
      <label for="username"><b>Username</b></label>
      <input type="text" placeholder="Enter Username" name="username" required>

      <label for="password"><b>Password</b></label>
      <input type="password" placeholder="Enter Password" name="password" required>
        
      <button type="submit">Login</button>
    </div>

  </form>
</div>

<script>
// Get the modal
var modal = document.getElementById('id01');

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
}
</script>

templates/users/signup.html
{% extends 'base.html' %}
{% block title %}Sign up{% endblock title %}
{% block content %}
<div class="signup">
  <form action="" method="POST" class="signup-form">
    {% csrf_token %}

    {% for non_field_error in form.non_field_errors %}
      <p class="error">{{ non_field_error }}</p>
    {% endfor %}

    {% for field in form %}
    <div class="field">
      <label for="{{ field.id_for_label }}">{{ field.label }}</label>
      {{ field }}
      {% for error in field.errors %}
      <p class="error">{{ error }}</p>
      {% endfor %}
      {% if field.help_text %}
        <p class="help">{{ field.help_text|safe }}</p>
      {% endif %}
    </div>
  {% endfor %}
    <input type="submit" value="Sign up">
  </form>
</div>
{% endblock content %}